apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailtura.envSecretName" . }}
  labels:
    {{- include "mailtura.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "mailtura.databaseUrl" . | quote }}
  STACKGRES_SUPERUSER_USERNAME: {{ .Values.stackgres.credentials.superuser.username | quote }}
  STACKGRES_SUPERUSER_PASSWORD: {{ .Values.stackgres.credentials.superuser.password | quote }}
  TEMPORAL_ADDRESS: {{ include "mailtura.temporalAddress" . | quote }}
  TEMPORAL_NAMESPACE: {{ .Values.env.temporal.namespace | quote }}
  TEMPORAL_TASK_QUEUE: {{ .Values.env.temporal.taskQueue | quote }}
  API_BASE_URL: {{ include "mailtura.apiBaseUrl" . | quote }}
  MAILTURA_AUTH_SECRET: {{ required "env.mailturaAuthSecret is required" .Values.env.mailturaAuthSecret | quote }}
